# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shun-Lung's Blog
description:      'Data Science'
baseurl:          /

author:           Shun-Lung, Chang
name:             'Shun-Lung, Chang'
url:              https://connerchang.github.io/

paginate:         5

# Custom vars
mail_address:      edi7709@gmail.com
github_username:   connerchang
linkedin_username: connerchang
