# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            Shun-Lung's Blog
description:      'Programming / Data Science'
baseurl:          /

author:           Shun-Lung, Chang
name:             'Shun-Lung, Chang'
url:              https://connerchang.github.io/

paginate:         5

# Custom vars
version:          0.1.0

github:           https://github.com/ConnerChang         
